# Site settings
title: Strict Machine
description: "Articles and also some articles"
baseurl: ""
url: "https://strict-machine.com"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - divshot.json

kramdown:
  input: GFM
  extensions: [smart]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
