# Site settings
title: George Gritsouk
email: george.gritsouk@gmail.com
description: "George Gritsouk, personal site. Articles about development, mostly."
baseurl: ""
url: "https://gggritso.com"
twitter_username: gggritso
github_username:  gggritso

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - divshot.json

kramdown:
  input: GFM
  extensions: [smart]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
